# Generated by Django 5.1.4 on 2024-12-05 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
                ('bookname', models.CharField(max_length=100)),
                ('tamilname', models.CharField(max_length=10)),
                ('chapter', models.CharField(max_length=100)),
                ('versecount', models.CharField(max_length=100)),
                ('verse', models.TextField()),
                ('kjv', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewTestamentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('booknametamil', models.CharField(max_length=100, null=True)),
                ('totalchapters', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OldTestamentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('booknametamil', models.CharField(max_length=100, null=True)),
                ('totalchapters', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newchapter_number', models.IntegerField()),
                ('booknew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.newtestamentbook')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.oldtestamentbook')),
            ],
        ),
    ]
