# Generated by Django 5.1.4 on 2024-12-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dailyverse'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyverse_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('tamilname', models.CharField(max_length=10)),
                ('chapter', models.IntegerField(max_length=100)),
                ('versecount', models.IntegerField(max_length=100)),
                ('verse', models.TextField()),
                ('kjv', models.TextField()),
            ],
        ),
    ]
