# Generated by Django 5.1.4 on 2024-12-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_dailyverse_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse_of_the_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('bookname', models.CharField(max_length=20)),
                ('tamilname', models.CharField(max_length=20)),
                ('chapter', models.IntegerField()),
                ('versecount', models.IntegerField()),
                ('verse', models.TextField()),
                ('kjv', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='dailyverse_day',
            name='chapter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailyverse_day',
            name='versecount',
            field=models.IntegerField(),
        ),
    ]
