# Generated by Django 5.1.4 on 2024-12-16 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_taxonomybiblestudy_biblereferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblereferences',
            name='tamil_bible_message',
        ),
    ]
