# Generated by Django 5.1.4 on 2024-12-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_biblereferences_tamil_bible_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblereferences',
            name='bookname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
