# Generated by Django 5.1.4 on 2024-12-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_biblereferences_bookname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblereferences',
            name='bookname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
