# Generated by Django 5.1.4 on 2024-12-20 06:12

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_biblereferences_tamil_bible_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorCermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('tamil_bible_message', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_references', to='myapp.author')),
                ('select_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_tags', to='myapp.taxonomybiblestudy')),
            ],
        ),
        migrations.DeleteModel(
            name='BibleReferences',
        ),
    ]
