# Generated by Django 5.1.4 on 2024-12-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_authorcermon_delete_biblereferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorcermon',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
