# Generated by Django 5.1.4 on 2024-12-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_authorcermon_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorCermon',
            new_name='Authormessage',
        ),
    ]
