# Generated by Django 5.1.4 on 2025-01-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_authorcermon_authormessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormessage',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
