# Generated by Django 5.1.3 on 2025-01-31 06:56

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_authormessage_select_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bible_reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', ckeditor.fields.RichTextField(null=True)),
                ('booknametamil', models.CharField(max_length=20)),
                ('chapter', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('view_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='myapp.author')),
            ],
        ),
    ]
