# Generated by Django 5.1.4 on 2025-02-05 07:34

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_bible_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bible_kavithaigal_tamil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', ckeditor.fields.RichTextField(null=True)),
                ('url', models.CharField(max_length=100)),
                ('view_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kavithaigal', to='myapp.author')),
            ],
        ),
    ]
