# Generated by Django 5.1.4 on 2025-02-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_booknametamil_alter_bible_reference_booknametamil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bible_reference',
            name='booknametamil',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='BookNameTamil',
        ),
    ]
