# Generated by Django 5.1.4 on 2025-02-13 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_bible_reference_booknametamil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNameTamil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bible_reference',
            name='booknametamil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.author'),
        ),
    ]
