# Generated by Django 5.1.4 on 2025-02-13 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_booknametamil_alter_bible_reference_booknametamil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booknametamil',
            old_name='book',
            new_name='booknametamil',
        ),
        migrations.AlterField(
            model_name='bible_reference',
            name='booknametamil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.booknametamil'),
        ),
    ]
