# Generated by Django 5.1.4 on 2025-02-14 09:02

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_book_booknametamil_booknametamil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prasanga_Kuripugal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('tamil_bible_message', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prasangam_kuripugal_author', to='myapp.author')),
                ('select_tag', models.ManyToManyField(related_name='prasangam_selected_tags', to='myapp.taxonomybiblestudy')),
            ],
        ),
    ]
