# Generated by Django 5.1.4 on 2025-02-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_prasanga_kuripugal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prasanga_kuripugal',
            name='select_tag',
            field=models.ManyToManyField(null=True, related_name='prasangam_selected_tags', to='myapp.taxonomybiblestudy'),
        ),
    ]
